name: autoplex
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - blas=2.304=openblas
  - blas-devel=3.11.0=4_h1ea3ea9_openblas
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - flask=3.1.2=pyhd8ed1ab_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jpeg=9e=h166bdaf_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.1.1=h0131e85_1
  - libblas=3.11.0=4_h4a7cf45_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.11.0=4_h0358290_openblas
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran=3.0.0=1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.84.4=h77a78f3_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.11.0=4_h47877c9_openblas
  - liblapacke=3.11.0=4_h6ae95b6_openblas
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-base=3.5.2=py310h5701ce4_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nomkl=3.0=0
  - numpy=1.26.4=py310hc213724_1
  - numpy-base=1.26.4=py310hf387b04_1
  - openblas=0.3.30=h5426c36_2
  - openblas-devel=0.3.30=h557178c_2
  - openssl=3.0.18=hd6dcaed_0
  - pcre2=10.46=hf426167_0
  - pillow=12.0.0=py310h3b88751_1
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - readline=8.3=hc2a1206_0
  - scipy=1.15.3=py310ha592af2_1
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - unicodedata2=14.0.0=py310h5764c6d_1
  - werkzeug=3.1.4=pyhcf101f3_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - accessible-pygments==0.0.5
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - annotated-types==0.7.0
      - arrow==1.4.0
      - ase==3.24.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - atomate2==0.0.21
      - atpublic==6.0.2
      - attrs==25.4.0
      - autodoc-pydantic==2.2.0
      - autoplex==0.2.0
      - babel==2.17.0
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - boto3==1.40.61
      - botocore==1.40.61
      - calorine==3.0
      - cclib==1.8.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - click==8.2.0
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - coverage==7.11.0
      - cryptography==46.0.3
      - custodian==2025.4.14
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dgl==2.1.0
      - distlib==0.4.0
      - dnspython==2.8.0
      - docutils==0.21.2
      - dscribe==2.1.1
      - e3nn==0.4.4
      - emmet-core==0.84.5
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - f90wrap==0.2.16
      - fabric==3.2.2
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - flufl-lock==8.2.0
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.2.4
      - h5py==3.15.1
      - hiphive==1.4
      - identify==2.6.15
      - idna==3.11
      - ijson==3.3.0
      - imageio==2.37.0
      - imagesize==1.4.1
      - iniconfig==2.3.0
      - invoke==2.2.1
      - ipykernel==7.1.0
      - ipython==8.37.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jmespath==1.0.1
      - jobflow==0.1.19
      - jobflow-remote==0.1.5
      - joblib==1.5.2
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-cache==1.0.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.9
      - latexcodec==3.0.1
      - lazy-loader==0.4
      - lightning==2.5.1
      - lightning-utilities==0.14.3
      - llvmlite==0.45.1
      - lmdb==1.7.5
      - lobsterpy==0.4.9
      - mace-torch==0.3.13
      - maggma==0.72.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matgl==1.2.7
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - matscipy==1.1.1
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - mongomock==4.3.0
      - monty==2025.3.3
      - mp-api==0.45.4
      - mp-pyrho==0.5.1
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - myst-nb==1.3.0
      - myst-parser==4.0.1
      - narwhals==2.10.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nbmake==1.5.5
      - nequip==0.6.1
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nodeenv==1.9.1
      - numba==0.62.1
      - numpydoc==1.9.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - orjson==3.11.4
      - packaging==24.2
      - palettable==3.3.3
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - paramiko==4.0.0
      - parso==0.8.5
      - periodictable==2.0.2
      - pexpect==4.9.0
      - phonopy==2.30.1
      - pip==25.3
      - platformdirs==4.5.0
      - plotly==6.3.1
      - pluggy==1.6.0
      - pre-commit==4.3.0
      - prettytable==3.16.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybtex==0.25.1
      - pycparser==2.23
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydantic-settings==2.9.1
      - pydash==8.0.5
      - pydata-sphinx-theme==0.16.1
      - pygments==2.19.2
      - pymatgen==2025.2.18
      - pymatgen-analysis-defects==2025.1.18
      - pymongo==4.10.1
      - pynacl==1.6.0
      - pytest==8.4.2
      - pytest-cov==7.0.0
      - pytest-mock==3.15.1
      - pytest-split==0.10.0
      - python-dotenv==1.2.1
      - python-hostlist==2.3.0
      - python-ulid==3.0.0
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - qtoolkit==0.1.6
      - quippy-ase==0.9.14
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3987==1.3.8
      - rich==13.9.4
      - rpds-py==0.28.0
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.14
      - s3transfer==0.14.0
      - schedule==1.2.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - seekpath==2.1.0
      - sentinels==1.1.1
      - shellingham==1.5.4
      - smart-open==7.4.1
      - smmap==5.0.2
      - snowballstemmer==3.0.1
      - soupsieve==2.8
      - sparse==0.17.0
      - spglib==2.6.0
      - sphinx==8.1.3
      - sphinx-book-theme==1.1.0
      - sphinx-copybutton==0.5.2
      - sphinx-design==0.6.1
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-mermaid==1.0.0
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.44
      - sshtunnel==0.4.0
      - stack-data==0.6.3
      - supervisor==4.3.0
      - symfc==1.5.4
      - sympy==1.14.0
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tinycss2==1.4.0
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.9.1+cu126
      - torch-ema==0.3
      - torch-runstats==0.2.0
      - torchdata==0.7.1
      - torchmetrics==1.8.2
      - torchvision==0.24.1+cu126
      - tornado==6.5.2
      - tqdm==4.67.1
      - trainstation==1.2
      - traitlets==5.14.3
      - triton==3.5.1
      - typer==0.20.0
      - types-setuptools==80.9.0.20250822
      - typing==3.7.4.3
      - typing-extensions==4.13.2
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uncertainties==3.2.3
      - uri-template==1.3.0
      - urllib3==2.5.0
      - virtualenv==20.35.4
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - wrapt==1.17.3
      - yarl==1.22.0
prefix: /u/vld/sedm7085/miniconda3/envs/autoplex
